default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sff_development

test:
  <<: *default
  database: sff_test

production:
  <<: *default
  database: sff_production
  username: sff
  password: <%= ENV['SFF_DATABASE_PASSWORD'] %>
